apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: sandbox-pizzly
  name: sandbox-pizzly-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: nginx-ingress
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/server-snippet: |
      large_client_header_buffers 4 16k;
  labels:
    product: sandbox-pizzly
    app.kubernetes.io/name: "sandbox-pizzly-nginx-ingress"
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/part-of: "sandbox-pizzly"
spec:
  tls:
    - hosts:
        - pizzly.integrations-lab-forge.deltatre.digital
      secretName: letsencrypt-certs
  rules:
    - host: pizzly.integrations-lab-forge.deltatre.digital
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: sandbox-pizzly-widget
              servicePort: 8080
