apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox-pizzly
  name: sandbox-pizzly-widget
  labels:
    app: sandbox-pizzly-widget
    product: sandbox-pizzly
    app.kubernetes.io/name: "sandbox-pizzly-widget"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "davide"
    app.kubernetes.io/component: "sandbox-pizzly-widget"
    app.kubernetes.io/part-of: "sandbox-pizzly"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-pizzly-widget
  template:
    metadata:
      labels:
        app: sandbox-pizzly-widget
    spec:
      initContainers:
        - name: init-sandbox-pizzly-widget
          image: davidep931/pizzly-proxy:latest
          command:
            ["/bin/sh", "-c", "cp -R /home/node/app/integrations/* /tmp/"]
          volumeMounts:
            - name: pizzlystorage
              mountPath: /tmp
      containers:
        - name: sandbox-pizzly-widget
          image: davidep931/pizzly-proxy:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: DASHBOARD_USERNAME
              value: "admin"
            - name: DASHBOARD_PASSWORD
              value: "admin"
            - name: SECRET_KEY
              value: "devSecretKey"
            - name: PUBLISHABLE_KEY
              value: "devPubKey"
            - name: PROXY_USES_SECRET_KEY_ONLY
              value: "FALSE"
            - name: COOKIE_SECRET
              value: "devCookieSecret"
            - name: AUTH_CALLBACK_URL
              value: "https://pizzly.integrations-lab-forge.deltatre.digital/auth/callback"
            - name: DB_HOST
              value: "postgres.postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "postgresdb"
            - name: DB_USER
              value: "postgresadmin"
            - name: DB_PASSWORD
              value: "admin123"
            - name: PORT
              value: "8080"
          volumeMounts:
            - mountPath: "/home/node/app/integrations"
              name: pizzlystorage
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              cpu: "75m"
              memory: "200Mi"
      volumes:
        - name: pizzlystorage
          persistentVolumeClaim:
            claimName: sandbox-pizzly-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: sandbox-pizzly
  name: sandbox-pizzly-widget
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sandbox-pizzly-widget
