apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: sandbox-pizzly
  name: sandbox-pizzly-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: nginx-ingress
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    product: sandbox-pizzly
    app.kubernetes.io/name: "sandbox-pizzly-nginx-ingress"
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/part-of: "sandbox-pizzly"
spec:
  tls:
    - hosts:
        - pizzly.sandbox.deltatre.digital
      secretName: letsencrypt-certs
  rules:
    - host: pizzly.sandbox.deltatre.digital
      http:
        paths:
          - path: /
            backend:
              serviceName: sandbox-pizzly-widget
              servicePort: 8080
