apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-pizzly
  labels:
    product: sandbox-pizzly
    app.kubernetes.io/name: "sandbox-pizzly"
    app.kubernetes.io/component: "namespace"
    app.kubernetes.io/part-of: "sandbox-pizzly"
