kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: products-pizzly
  name: products-pizzly-pv-volume
  labels:
    type: local
    app: products
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: products-pizzly
  name: products-pizzly-pv-claim
  labels:
    app: products
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
