apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: products-pizzly
  name: products-pizzly-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    product: products-pizzly
    app.kubernetes.io/name: "products-pizzly-nginx-ingress"
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/part-of: "products-pizzly"
spec:
  tls:
    - hosts:
        - pizzly.products.deltatre.digital
      secretName: letsencrypt-certs
  rules:
    - host: pizzly.products.deltatre.digital
      http:
        paths:
          - path: /
            backend:
              serviceName: products-pizzly-widget
              servicePort: 8080
